apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
{% if values.tags %}
  tags:
{% for tag in values.tags %}
    - ${{ tag }}
{% endfor %}
{% endif %}
spec:
  type: openapi
  lifecycle: dev
  owner: ${{ values.owner }}
  
${{ values.tags }}
${{ values.tags[0] }}
