apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: BIO YUD API
  description: The YUD API
  tags:
    - yud
    - demo
spec:
  type: openapi
  lifecycle: dev
  owner: group:default/grp_-_platform_experience_team
  definition: 
    $text: https://github.com/alexv80/BackstagePOC/blob/main/APIs/inventoryApiDefinition.json
