apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags: ${{ values.tags }}
spec:
  type: openapi
  lifecycle: dev
  owner: ${{ values.owner }}
