apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
{%- for tag in values.tags %}
{%- if loop.first %}
  tags:
{%- endif %}
    - ${{ tag }}
{%- endfor %}
spec:
  type: openapi
  lifecycle: dev
  owner: ${{ values.owner }}
