name: Test worflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: .
      
